
package com.netmng.websvc.soap.param._interface;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.6.9
 * 2013-09-11T15:22:33.073+09:00
 * Generated source version: 2.6.9
 */

@WebFault(name = "querySummarySyncFailed", targetNamespace = "http://schemas.ogf.org/nsi/2013/07/connection/types")
public class QuerySummarySyncFailed extends Exception {
    
    private com.netmng.websvc.soap.param.types.QueryFailedType querySummarySyncFailed;

    public QuerySummarySyncFailed() {
        super();
    }
    
    public QuerySummarySyncFailed(String message) {
        super(message);
    }
    
    public QuerySummarySyncFailed(String message, Throwable cause) {
        super(message, cause);
    }

    public QuerySummarySyncFailed(String message, com.netmng.websvc.soap.param.types.QueryFailedType querySummarySyncFailed) {
        super(message);
        this.querySummarySyncFailed = querySummarySyncFailed;
    }

    public QuerySummarySyncFailed(String message, com.netmng.websvc.soap.param.types.QueryFailedType querySummarySyncFailed, Throwable cause) {
        super(message, cause);
        this.querySummarySyncFailed = querySummarySyncFailed;
    }

    public com.netmng.websvc.soap.param.types.QueryFailedType getFaultInfo() {
        return this.querySummarySyncFailed;
    }
}
