
package com.netmng.websvc.soap.param._interface;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.6.9
 * 2013-09-11T15:22:33.064+09:00
 * Generated source version: 2.6.9
 */

@WebFault(name = "queryNotificationSyncFailed", targetNamespace = "http://schemas.ogf.org/nsi/2013/07/connection/types")
public class QueryNotificationSyncFailed extends Exception {
    
    private com.netmng.websvc.soap.param.types.QueryFailedType queryNotificationSyncFailed;

    public QueryNotificationSyncFailed() {
        super();
    }
    
    public QueryNotificationSyncFailed(String message) {
        super(message);
    }
    
    public QueryNotificationSyncFailed(String message, Throwable cause) {
        super(message, cause);
    }

    public QueryNotificationSyncFailed(String message, com.netmng.websvc.soap.param.types.QueryFailedType queryNotificationSyncFailed) {
        super(message);
        this.queryNotificationSyncFailed = queryNotificationSyncFailed;
    }

    public QueryNotificationSyncFailed(String message, com.netmng.websvc.soap.param.types.QueryFailedType queryNotificationSyncFailed, Throwable cause) {
        super(message, cause);
        this.queryNotificationSyncFailed = queryNotificationSyncFailed;
    }

    public com.netmng.websvc.soap.param.types.QueryFailedType getFaultInfo() {
        return this.queryNotificationSyncFailed;
    }
}
