
package com.netmng.websvc.soap.param._interface;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.6.9
 * 2013-09-11T15:22:33.054+09:00
 * Generated source version: 2.6.9
 */

@WebFault(name = "serviceException", targetNamespace = "http://schemas.ogf.org/nsi/2013/07/connection/types")
public class ServiceException extends Exception {
    
    private com.netmng.websvc.soap.svc.types.ServiceExceptionType serviceException;

    public ServiceException() {
        super();
    }
    
    public ServiceException(String message) {
        super(message);
    }
    
    public ServiceException(String message, Throwable cause) {
        super(message, cause);
    }

    public ServiceException(String message, com.netmng.websvc.soap.svc.types.ServiceExceptionType serviceException) {
        super(message);
        this.serviceException = serviceException;
    }

    public ServiceException(String message, com.netmng.websvc.soap.svc.types.ServiceExceptionType serviceException, Throwable cause) {
        super(message, cause);
        this.serviceException = serviceException;
    }

    public com.netmng.websvc.soap.svc.types.ServiceExceptionType getFaultInfo() {
        return this.serviceException;
    }
}
