package com.netmng.websvc.soap.svc.provider;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.9
 * 2013-09-11T15:22:33.083+09:00
 * Generated source version: 2.6.9
 * 
 */
@WebService(targetNamespace = "http://schemas.ogf.org/nsi/2013/07/connection/provider", name = "ConnectionProviderPort")
@XmlSeeAlso({	com.netmng.websvc.soap.svc.types.ObjectFactory.class, 
				com.netmng.websvc.soap.param.types.ObjectFactory.class, 
				com.netmng.websvc.soap.svc.header.ObjectFactory.class, 
				com.netmng.websvc.soap.assertion.ObjectFactory.class, 
				com.netmng.websvc.soap.result.xmlenc.ObjectFactory.class, 
				com.netmng.websvc.soap.result.xmldsig.ObjectFactory.class,
				com.netmng.websvc.soap.svc.services.point2point.ObjectFactory.class
			})


public interface ConnectionProviderPort {

	/**
     * The reserve message is sent from a Requester NSA to a Provider
     * NSA when a new reservation is being requested, or a modification
     * to an existing reservation is required. The reserveResponse
     * indicates that the Provider NSA has accepted the reservation
     * request for processing and has assigned it the returned
     * connectionId. A reserveConfirmed or reserveFailed message will
     * be sent asynchronously to the Requester NSA when reserve 
     * operation has completed processing.
     *             
     */
    @RequestWrapper(localName = "reserve", targetNamespace = "http://schemas.ogf.org/nsi/2013/07/connection/types", className = "com.netmng.websvc.soap.param.types.ReserveType")
    @WebMethod(action = "http://schemas.ogf.org/nsi/2013/07/connection/service/reserve")
    @ResponseWrapper(localName = "reserveResponse", targetNamespace = "http://schemas.ogf.org/nsi/2013/07/connection/types", className = "com.netmng.websvc.soap.param.types.ReserveResponseType")
    public void reserve(
        @WebParam(mode = WebParam.Mode.INOUT, name = "connectionId", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> connectionId,
        @WebParam(name = "globalReservationId", targetNamespace = "")
        java.lang.String globalReservationId,
        @WebParam(name = "description", targetNamespace = "")
        java.lang.String description,
        @WebParam(name = "criteria", targetNamespace = "")
        com.netmng.websvc.soap.param.types.ReservationRequestCriteriaType criteria
    ) throws com.netmng.websvc.soap.param._interface.ServiceException;
    
    /**
     * The reserveCommit message is sent from a Requester NSA to a
     * Provider NSA when a reservation or modification to an existing
     * reservation is being committed. The reserveCommitACK indicates
     * that the Provider NSA has accepted the modify request for
     * processing. A reserveCommitConfirmed or reserveCommitFailed message
     * will be sent asynchronously to the Requester NSA when reserve
     * or modify processing has completed.
     *             
     */
    @RequestWrapper(localName = "reserveCommit", targetNamespace = "http://schemas.ogf.org/nsi/2013/07/connection/types", className = "com.netmng.websvc.soap.param.types.GenericRequestType")
    @WebMethod(action = "http://schemas.ogf.org/nsi/2013/07/connection/service/reserveCommit")
    @ResponseWrapper(localName = "acknowledgment", targetNamespace = "http://schemas.ogf.org/nsi/2013/07/connection/types", className = "com.netmng.websvc.soap.param.types.GenericAcknowledgmentType")
    public void reserveCommit(
        @WebParam(name = "connectionId", targetNamespace = "")
        java.lang.String connectionId
    ) throws com.netmng.websvc.soap.param._interface.ServiceException;
    
    /**
     * The reserveAbort message is sent from a Requester NSA to a
     * Provider NSA when a cancellation to an existing reserve or
     * modify operation is being requested. The reserveAbortACK
     * indicates that the Provider NSA has accepted the reserveAbort
     * request for processing. A reserveAbortConfirmed or
     * reserveAbortFailed message will be sent asynchronously to the
     * Requester NSA when reserveAbort processing has completed.
     *             
     */
    @RequestWrapper(localName = "reserveAbort", targetNamespace = "http://schemas.ogf.org/nsi/2013/07/connection/types", className = "com.netmng.websvc.soap.param.types.GenericRequestType")
    @WebMethod(action = "http://schemas.ogf.org/nsi/2013/07/connection/service/reserveAbort")
    @ResponseWrapper(localName = "acknowledgment", targetNamespace = "http://schemas.ogf.org/nsi/2013/07/connection/types", className = "com.netmng.websvc.soap.param.types.GenericAcknowledgmentType")
    public void reserveAbort(
        @WebParam(name = "connectionId", targetNamespace = "")
        java.lang.String connectionId
    ) throws com.netmng.websvc.soap.param._interface.ServiceException;
    
    /**
     * The provision message is sent from a Requester NSA to a Provider
     * NSA when an existing reservation is to be transitioned into a
     * provisioned state. The provisionACK indicates that the Provider
     * NSA has accepted the provision request for processing. A
     * provisionConfirmed message will be sent asynchronously to the
     * Requester NSA when provision processing has completed.  There is
     * no associated Failed message for this operation.
     *             
     */
    @RequestWrapper(localName = "provision", targetNamespace = "http://schemas.ogf.org/nsi/2013/07/connection/types", className = "com.netmng.websvc.soap.param.types.GenericRequestType")
    @WebMethod(action = "http://schemas.ogf.org/nsi/2013/07/connection/service/provision")
    @ResponseWrapper(localName = "acknowledgment", targetNamespace = "http://schemas.ogf.org/nsi/2013/07/connection/types", className = "com.netmng.websvc.soap.param.types.GenericAcknowledgmentType")
    public void provision(
        @WebParam(name = "connectionId", targetNamespace = "")
        java.lang.String connectionId
    ) throws com.netmng.websvc.soap.param._interface.ServiceException;
    
    /**
     * The release message is sent from a Requester NSA to a Provider
     * NSA when an existing reservation is to be transitioned into a
     * released state. The releaseACK indicates that the Provider NSA
     * has accepted the release request for processing. A
     * releaseConfirmed message will be sent asynchronously to the
     * Requester NSA when release processing has completed.  There is
     * no associated Failed message for this operation.
     *             
     */
    @RequestWrapper(localName = "release", targetNamespace = "http://schemas.ogf.org/nsi/2013/07/connection/types", className = "com.netmng.websvc.soap.param.types.GenericRequestType")
    @WebMethod(action = "http://schemas.ogf.org/nsi/2013/07/connection/service/release")
    @ResponseWrapper(localName = "acknowledgment", targetNamespace = "http://schemas.ogf.org/nsi/2013/07/connection/types", className = "com.netmng.websvc.soap.param.types.GenericAcknowledgmentType")
    public void release(
        @WebParam(name = "connectionId", targetNamespace = "")
        java.lang.String connectionId
    ) throws com.netmng.websvc.soap.param._interface.ServiceException;

    /**
     * The terminate message is sent from a Requester NSA to a Provider
     * NSA when an existing reservation is to be terminated. The
     * terminateACK indicates that the Provider NSA has accepted the
     * terminate request for processing. A terminateConfirmed or
     * terminateFailed message will be sent asynchronously to the Requester
     * NSA when terminate processing has completed.
     *             
     */
    /*@RequestWrapper(localName = "terminate", targetNamespace = "http://schemas.ogf.org/nsi/2013/07/connection/types", className = "org.ogf.schemas.nsi._2013._07.connection.types.GenericRequestType")*/
    @RequestWrapper(localName = "terminate", targetNamespace = "http://schemas.ogf.org/nsi/2013/07/connection/types", className = "com.netmng.websvc.soap.param.types.GenericRequestType")
    @WebMethod(action = "http://schemas.ogf.org/nsi/2013/07/connection/service/terminate")
    @ResponseWrapper(localName = "acknowledgment", targetNamespace = "http://schemas.ogf.org/nsi/2013/07/connection/types", className = "com.netmng.websvc.soap.param.types.GenericAcknowledgmentType")
    public void terminate(
        @WebParam(name = "connectionId", targetNamespace = "")
        java.lang.String connectionId
    ) throws com.netmng.websvc.soap.param._interface.ServiceException;

    /**
     * The querySummary message is sent from a Requester NSA to a
     * Provider NSA to determine the status of existing reservations.
     * The querySummaryACK indicates that the target NSA has
     * accepted the querySummary request for processing. A
     * querySummaryConfirmed or querySummaryFailed message will be
     * sent asynchronously to the requesting NSA when querySummary
     * processing has completed.
     *             
     */
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "acknowledgment", targetNamespace = "http://schemas.ogf.org/nsi/2013/07/connection/types", partName = "acknowledgment")
    @WebMethod(action = "http://schemas.ogf.org/nsi/2013/07/connection/service/querySummary")
    public com.netmng.websvc.soap.param.types.GenericAcknowledgmentType querySummary(
        @WebParam(partName = "querySummary", name = "querySummary", targetNamespace = "http://schemas.ogf.org/nsi/2013/07/connection/types")
        com.netmng.websvc.soap.param.types.QueryType querySummary
    ) throws com.netmng.websvc.soap.param._interface.ServiceException;
    
    /**
     * The queryRecursive message can be sent from either a Provider or
     * Requester NSA to determine the status of existing reservations.
     * The queryRecursiveACK indicates that the target NSA has accepted
     * the queryRecursive request for processing. A queryRecursiveConfirmed
     * or queryRecursiveFailed message will be sent asynchronously to the
     * requesting NSA when query processing has completed.
     *             
     */
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "acknowledgment", targetNamespace = "http://schemas.ogf.org/nsi/2013/07/connection/types", partName = "acknowledgment")
    @WebMethod(action = "http://schemas.ogf.org/nsi/2013/07/connection/service/queryRecursive")
    public com.netmng.websvc.soap.param.types.GenericAcknowledgmentType queryRecursive(
        @WebParam(partName = "queryRecursive", name = "queryRecursive", targetNamespace = "http://schemas.ogf.org/nsi/2013/07/connection/types")
        com.netmng.websvc.soap.param.types.QueryType queryRecursive
    ) throws com.netmng.websvc.soap.param._interface.ServiceException;

    /**
     * The querySummarySync message can be sent from a Requester NSA
     * to determine the status of existing reservations on the Provider
     * NSA. The querySummarySync is a synchronous operation that will
     * block until the results of the query operation have been
     * collected.  These results will be returned in the SOAP
     * response.
     *             
     */
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "querySummarySyncConfirmed", targetNamespace = "http://schemas.ogf.org/nsi/2013/07/connection/types", partName = "querySummarySyncConfirmed")
    @WebMethod(action = "http://schemas.ogf.org/nsi/2013/07/connection/service/querySummarySync")
    public com.netmng.websvc.soap.param.types.QuerySummaryConfirmedType querySummarySync(
        @WebParam(partName = "querySummarySync", name = "querySummarySync", targetNamespace = "http://schemas.ogf.org/nsi/2013/07/connection/types")
        com.netmng.websvc.soap.param.types.QueryType querySummarySync
    ) throws com.netmng.websvc.soap.param._interface.QuerySummarySyncFailed;
    
    /**
     * The queryNotification message is sent from a Requester NSA
     * to a Provider NSA to retrieve notifications against an existing
     * reservation residing on the Provider NSA. QueryNotification is an
     * asynchronous operation that will return results of the operation
     * to the Requester NSA's SOAP endpoint specified in the NSI header
     * replyTo field.
     *             
     */
    /*@RequestWrapper(localName = "queryNotification", targetNamespace = "http://schemas.ogf.org/nsi/2013/07/connection/types", className = "org.ogf.schemas.nsi._2013._07.connection.types.QueryNotificationType")*/
    @RequestWrapper(localName = "queryNotification", targetNamespace = "http://schemas.ogf.org/nsi/2013/07/connection/types", className = "com.netmng.websvc.soap.param.types.QueryNotificationType")
    @WebMethod(action = "http://schemas.ogf.org/nsi/2013/07/connection/service/queryNotification")
    @ResponseWrapper(localName = "acknowledgment", targetNamespace = "http://schemas.ogf.org/nsi/2013/07/connection/types", className = "com.netmng.websvc.soap.param.types.GenericAcknowledgmentType")
    public void queryNotification(
        @WebParam(name = "connectionId", targetNamespace = "")
        java.lang.String connectionId,
        @WebParam(name = "startNotificationId", targetNamespace = "")
        java.lang.Integer startNotificationId,
        @WebParam(name = "endNotificationId", targetNamespace = "")
        java.lang.Integer endNotificationId
    ) throws com.netmng.websvc.soap.param._interface.ServiceException;

    /**
     * The queryNotificationSync message can be sent from a Requester NSA
     * to notifications against an existing reservations on the Provider
     * NSA. The queryNotificationSync is a synchronous operation that
     * will block until the results of the query operation have been
     * collected.  These results will be returned in the SOAP response.
     *             
     */
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "queryNotificationSyncConfirmed", targetNamespace = "http://schemas.ogf.org/nsi/2013/07/connection/types", partName = "queryNotificationSyncConfirmed")
    @WebMethod(action = "http://schemas.ogf.org/nsi/2013/07/connection/service/queryNotificationSync")
    public com.netmng.websvc.soap.param.types.QueryNotificationConfirmedType queryNotificationSync(
        @WebParam(partName = "queryNotificationSync", name = "queryNotificationSync", targetNamespace = "http://schemas.ogf.org/nsi/2013/07/connection/types")
        com.netmng.websvc.soap.param.types.QueryNotificationType queryNotificationSync
    ) throws com.netmng.websvc.soap.param._interface.QueryNotificationSyncFailed;

}
