//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.11.27 at 03:11:18 PM KST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://schemas.ogf.org/nml/2013/05/base#", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.netmng.websvc.soap.parser.inter.base;
