//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.09.06 at 03:19:28 PM KST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://schemas.ogf.org/nsi/2013/07/services/description")
package com.netmng.websvc.soap.svc.services.description;
