package com.netmng.websvc.soap.svc.requester;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.6
 * 2013-09-16T13:24:45.270+09:00
 * Generated source version: 2.7.6
 * 
 */
@WebService(targetNamespace = "http://schemas.ogf.org/nsi/2013/07/connection/requester", name = "ConnectionRequesterPort")
@XmlSeeAlso({	com.netmng.websvc.soap.svc.types.ObjectFactory.class, 
				com.netmng.websvc.soap.param.types.ObjectFactory.class, 
				com.netmng.websvc.soap.svc.header.ObjectFactory.class, 
				com.netmng.websvc.soap.assertion.ObjectFactory.class, 
				com.netmng.websvc.soap.result.xmlenc.ObjectFactory.class, 
				com.netmng.websvc.soap.result.xmldsig.ObjectFactory.class,
				com.netmng.websvc.soap.svc.services.point2point.ObjectFactory.class
			})
public interface ConnectionRequesterPort {

	/**
     * This reserveConfirmed message is sent from a Provider NSA to
     * Requester NSA as an indication of a successful reservation. This
     * is in response to an original reserve request from the
     * associated Requester NSA.
     *             
     */
    @RequestWrapper(localName = "reserveConfirmed", targetNamespace = "http://schemas.ogf.org/nsi/2013/07/connection/types", className = "com.netmng.websvc.soap.param.types.ReserveConfirmedType")
    @WebMethod(action = "http://schemas.ogf.org/nsi/2013/07/connection/service/reserveConfirmed")
    @ResponseWrapper(localName = "acknowledgment", targetNamespace = "http://schemas.ogf.org/nsi/2013/07/connection/types", className = "com.netmng.websvc.soap.param.types.GenericAcknowledgmentType")
    public void reserveConfirmed(
        @WebParam(name = "connectionId", targetNamespace = "")
        java.lang.String connectionId,
        @WebParam(name = "globalReservationId", targetNamespace = "")
        java.lang.String globalReservationId,
        @WebParam(name = "description", targetNamespace = "")
        java.lang.String description,
        @WebParam(name = "criteria", targetNamespace = "")
        com.netmng.websvc.soap.param.types.ReservationConfirmCriteriaType criteria
    ) throws com.netmng.websvc.soap.param._interface.ServiceException;
    

    /**
     * This reserveFailed message is sent from a Provider NSA to
     * Requester NSA as an indication of a reserve failure. This
     * is in response to an original reserve request from the
     * associated Requester NSA.
     *             
     */
    @RequestWrapper(localName = "reserveFailed", targetNamespace = "http://schemas.ogf.org/nsi/2013/07/connection/types", className = "com.netmng.websvc.soap.param.types.GenericFailedType")
    @WebMethod(action = "http://schemas.ogf.org/nsi/2013/07/connection/service/reserveFailed")
    @ResponseWrapper(localName = "acknowledgment", targetNamespace = "http://schemas.ogf.org/nsi/2013/07/connection/types", className = "com.netmng.websvc.soap.param.types.GenericAcknowledgmentType")
    public void reserveFailed(
        @WebParam(name = "connectionId", targetNamespace = "")
        java.lang.String connectionId,
        @WebParam(name = "connectionStates", targetNamespace = "")
        com.netmng.websvc.soap.param.types.ConnectionStatesType connectionStates,
        @WebParam(name = "serviceException", targetNamespace = "")
        com.netmng.websvc.soap.svc.types.ServiceExceptionType serviceException
    ) throws com.netmng.websvc.soap.param._interface.ServiceException;

    /**
     * An autonomous message issued from a Provider NSA to Requester
     * NSA.  The acknowledgment indicates that the Requester NSA has
     * accepted the notification request for processing. There are no
     * associated confirmed or failed messages.
     *             
     */
    @RequestWrapper(localName = "reserveTimeout", targetNamespace = "http://schemas.ogf.org/nsi/2013/07/connection/types", className = "com.netmng.websvc.soap.param.types.ReserveTimeoutRequestType")
    @WebMethod(action = "http://schemas.ogf.org/nsi/2013/07/connection/service/reserveTimeout")
    @ResponseWrapper(localName = "acknowledgment", targetNamespace = "http://schemas.ogf.org/nsi/2013/07/connection/types", className = "com.netmng.websvc.soap.param.types.GenericAcknowledgmentType")
    public void reserveTimeout(
        @WebParam(name = "connectionId", targetNamespace = "")
        java.lang.String connectionId,
        @WebParam(name = "notificationId", targetNamespace = "")
        int notificationId,
        @WebParam(name = "timeStamp", targetNamespace = "")
        javax.xml.datatype.XMLGregorianCalendar timeStamp,
        @WebParam(name = "timeoutValue", targetNamespace = "")
        int timeoutValue,
        @WebParam(name = "originatingConnectionId", targetNamespace = "")
        java.lang.String originatingConnectionId,
        @WebParam(name = "originatingNSA", targetNamespace = "")
        java.lang.String originatingNSA
    ) throws com.netmng.websvc.soap.param._interface.ServiceException;
    
    /**
     * This reserveCommitConfirmed message is sent from a Provider NSA to
     * Requester NSA as an indication of a successful reserveCommit request.
     * This is in response to an original reserveCommit request from the
     * associated Requester NSA.
     *             
     */
    @RequestWrapper(localName = "reserveCommitConfirmed", targetNamespace = "http://schemas.ogf.org/nsi/2013/07/connection/types", className = "com.netmng.websvc.soap.param.types.GenericConfirmedType")
    @WebMethod(action = "http://schemas.ogf.org/nsi/2013/07/connection/service/reserveCommitConfirmed")
    @ResponseWrapper(localName = "acknowledgment", targetNamespace = "http://schemas.ogf.org/nsi/2013/07/connection/types", className = "com.netmng.websvc.soap.param.types.GenericAcknowledgmentType")
    public void reserveCommitConfirmed(
        @WebParam(name = "connectionId", targetNamespace = "")
        java.lang.String connectionId
    ) throws com.netmng.websvc.soap.param._interface.ServiceException;
    
    /**
     * This reserveCommitFailed message is sent from a Provider NSA to
     * Requester NSA as an indication of a modify failure. This
     * is in response to an original modify request from the
     * associated Requester NSA.
     *             
     */
    @RequestWrapper(localName = "reserveCommitFailed", targetNamespace = "http://schemas.ogf.org/nsi/2013/07/connection/types", className = "com.netmng.websvc.soap.param.types.GenericFailedType")
    @WebMethod(action = "http://schemas.ogf.org/nsi/2013/07/connection/service/reserveCommitFailed")
    @ResponseWrapper(localName = "acknowledgment", targetNamespace = "http://schemas.ogf.org/nsi/2013/07/connection/types", className = "com.netmng.websvc.soap.param.types.GenericAcknowledgmentType")
    public void reserveCommitFailed(
        @WebParam(name = "connectionId", targetNamespace = "")
        java.lang.String connectionId,
        @WebParam(name = "connectionStates", targetNamespace = "")
        com.netmng.websvc.soap.param.types.ConnectionStatesType connectionStates,
        @WebParam(name = "serviceException", targetNamespace = "")
        com.netmng.websvc.soap.svc.types.ServiceExceptionType serviceException
    ) throws com.netmng.websvc.soap.param._interface.ServiceException;
    
    /**
     * This reserveAbortConfirmed message is sent from a Provider NSA to
     * Requester NSA as an indication of a successful reserveAbort.
     * This is in response to an original reserveAbort request from the
     * associated Requester NSA.
     *             
     */
    @RequestWrapper(localName = "reserveAbortConfirmed", targetNamespace = "http://schemas.ogf.org/nsi/2013/07/connection/types", className = "com.netmng.websvc.soap.param.types.GenericConfirmedType")
    @WebMethod(action = "http://schemas.ogf.org/nsi/2013/07/connection/service/reserveAbortConfirmed")
    @ResponseWrapper(localName = "acknowledgment", targetNamespace = "http://schemas.ogf.org/nsi/2013/07/connection/types", className = "com.netmng.websvc.soap.param.types.GenericAcknowledgmentType")
    public void reserveAbortConfirmed(
        @WebParam(name = "connectionId", targetNamespace = "")
        java.lang.String connectionId
    ) throws com.netmng.websvc.soap.param._interface.ServiceException;
    
    /**
     * This provisionConfirmed message is sent from a Provider NSA to
     * Requester NSA as an indication of a successful provision operation.
     * This is in response to an original provision request from the
     * associated Requester NSA.
     *             
     */
    @RequestWrapper(localName = "provisionConfirmed", targetNamespace = "http://schemas.ogf.org/nsi/2013/07/connection/types", className = "com.netmng.websvc.soap.param.types.GenericConfirmedType")
    @WebMethod(action = "http://schemas.ogf.org/nsi/2013/07/connection/service/provisionConfirmed")
    @ResponseWrapper(localName = "acknowledgment", targetNamespace = "http://schemas.ogf.org/nsi/2013/07/connection/types", className = "com.netmng.websvc.soap.param.types.GenericAcknowledgmentType")
    public void provisionConfirmed(
        @WebParam(name = "connectionId", targetNamespace = "")
        java.lang.String connectionId
    ) throws com.netmng.websvc.soap.param._interface.ServiceException;

    /**
     * This releaseConfirmed message is sent from a Provider NSA to
     * Requester NSA as an indication of a successful release operation.
     * This is in response to an original release request from the
     * associated Requester NSA.
     *             
     */
    @RequestWrapper(localName = "releaseConfirmed", targetNamespace = "http://schemas.ogf.org/nsi/2013/07/connection/types", className = "com.netmng.websvc.soap.param.types.GenericConfirmedType")
    @WebMethod(action = "http://schemas.ogf.org/nsi/2013/07/connection/service/releaseConfirmed")
    @ResponseWrapper(localName = "acknowledgment", targetNamespace = "http://schemas.ogf.org/nsi/2013/07/connection/types", className = "com.netmng.websvc.soap.param.types.GenericAcknowledgmentType")
    public void releaseConfirmed(
        @WebParam(name = "connectionId", targetNamespace = "")
        java.lang.String connectionId
    ) throws com.netmng.websvc.soap.param._interface.ServiceException;

    /**
     * This terminateConfirmed message is sent from a Provider NSA to
     * Requester NSA as an indication of a successful terminate operation.
     * This is in response to an original terminate request from the
     * associated Requester NSA.
     *             
     */
    @RequestWrapper(localName = "terminateConfirmed", targetNamespace = "http://schemas.ogf.org/nsi/2013/07/connection/types", className = "com.netmng.websvc.soap.param.types.GenericConfirmedType")
    @WebMethod(action = "http://schemas.ogf.org/nsi/2013/07/connection/service/terminateConfirmed")
    @ResponseWrapper(localName = "acknowledgment", targetNamespace = "http://schemas.ogf.org/nsi/2013/07/connection/types", className = "com.netmng.websvc.soap.param.types.GenericAcknowledgmentType")
    public void terminateConfirmed(
        @WebParam(name = "connectionId", targetNamespace = "")
        java.lang.String connectionId
    ) throws com.netmng.websvc.soap.param._interface.ServiceException;

    /**
     * This querySummaryConfirmed message is sent from the target NSA to
     * requesting NSA as an indication of a successful querySummary
     * operation. This is in response to an original querySummary request
     * from the associated Requester NSA.
     *             
     */
    @RequestWrapper(localName = "querySummaryConfirmed", targetNamespace = "http://schemas.ogf.org/nsi/2013/07/connection/types", className = "com.netmng.websvc.soap.param.types.QuerySummaryConfirmedType")
    @WebMethod(action = "http://schemas.ogf.org/nsi/2013/07/connection/service/querySummaryConfirmed")
    @ResponseWrapper(localName = "acknowledgment", targetNamespace = "http://schemas.ogf.org/nsi/2013/07/connection/types", className = "com.netmng.websvc.soap.param.types.GenericAcknowledgmentType")
    public void querySummaryConfirmed(
        @WebParam(name = "reservation", targetNamespace = "")
        java.util.List<com.netmng.websvc.soap.param.types.QuerySummaryResultType> reservation
    ) throws com.netmng.websvc.soap.param._interface.ServiceException;
    
    /**
     * This querySummaryFailed message is sent from the target NSA to
     * requesting NSA as an indication of a querySummary operation
     * failure. This is in response to an original querySummary request
     * from the associated Requester NSA.
     *             
     */
    @RequestWrapper(localName = "querySummaryFailed", targetNamespace = "http://schemas.ogf.org/nsi/2013/07/connection/types", className = "com.netmng.websvc.soap.param.types.QueryFailedType")
    @WebMethod(action = "http://schemas.ogf.org/nsi/2013/07/connection/service/querySummaryFailed")
    @ResponseWrapper(localName = "acknowledgment", targetNamespace = "http://schemas.ogf.org/nsi/2013/07/connection/types", className = "com.netmng.websvc.soap.param.types.GenericAcknowledgmentType")
    public void querySummaryFailed(
        @WebParam(name = "serviceException", targetNamespace = "")
        com.netmng.websvc.soap.svc.types.ServiceExceptionType serviceException
    ) throws com.netmng.websvc.soap.param._interface.ServiceException;

    /**
     * This queryRecursiveConfirmed message is sent from the Provider NSA to
     * Requester NSA as an indication of a successful queryRecursive
     * operation. This is in response to an original queryRecursive request
     * from the associated Requester NSA.
     *             
     */
    @RequestWrapper(localName = "queryRecursiveConfirmed", targetNamespace = "http://schemas.ogf.org/nsi/2013/07/connection/types", className = "com.netmng.websvc.soap.param.types.QueryRecursiveConfirmedType")
    @WebMethod(action = "http://schemas.ogf.org/nsi/2013/07/connection/service/queryRecursiveConfirmed")
    @ResponseWrapper(localName = "acknowledgment", targetNamespace = "http://schemas.ogf.org/nsi/2013/07/connection/types", className = "com.netmng.websvc.soap.param.types.GenericAcknowledgmentType")
    public void queryRecursiveConfirmed(
        @WebParam(name = "reservation", targetNamespace = "")
        java.util.List<com.netmng.websvc.soap.param.types.QueryRecursiveResultType> reservation
    ) throws com.netmng.websvc.soap.param._interface.ServiceException;

    /**
     * This queryRecursiveFailed message is sent from the Provider NSA
     * to Requester NSA as an indication of a queryRecursive operation
     * failure. This is in response to an original queryRecursive
     * request from the associated Requester NSA.
     *             
     */
    @RequestWrapper(localName = "queryRecursiveFailed", targetNamespace = "http://schemas.ogf.org/nsi/2013/07/connection/types", className = "com.netmng.websvc.soap.param.types.QueryFailedType")
    @WebMethod(action = "http://schemas.ogf.org/nsi/2013/07/connection/service/queryRecursiveFailed")
    @ResponseWrapper(localName = "acknowledgment", targetNamespace = "http://schemas.ogf.org/nsi/2013/07/connection/types", className = "com.netmng.websvc.soap.param.types.GenericAcknowledgmentType")
    public void queryRecursiveFailed(
        @WebParam(name = "serviceException", targetNamespace = "")
        com.netmng.websvc.soap.svc.types.ServiceExceptionType serviceException
    ) throws com.netmng.websvc.soap.param._interface.ServiceException;    
    
    /**
     * This queryNotificationConfirmed message is sent from the Provider NSA to
     * Requester NSA as an indication of a successful queryNotification
     * operation. This is in response to an original queryNotification request
     * from the associated Requester NSA.
     *             
     */
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "acknowledgment", targetNamespace = "http://schemas.ogf.org/nsi/2013/07/connection/types", partName = "acknowledgment")
    @WebMethod(action = "http://schemas.ogf.org/nsi/2013/07/connection/service/queryNotificationConfirmed")
    public com.netmng.websvc.soap.param.types.GenericAcknowledgmentType queryNotificationConfirmed(
        @WebParam(partName = "queryNotificationConfirmed", name = "queryNotificationConfirmed", targetNamespace = "http://schemas.ogf.org/nsi/2013/07/connection/types")
        com.netmng.websvc.soap.param.types.QueryNotificationConfirmedType queryNotificationConfirmed
    ) throws com.netmng.websvc.soap.param._interface.ServiceException;
    
    /**
     * This queryNotificationFailed message is sent from the Provider NSA to
     * Requester NSA as an indication of a queryNotification operation
     * failure. This is in response to an original queryNotification request
     * from the associated Requester NSA.
     *             
     */
    @RequestWrapper(localName = "queryNotificationFailed", targetNamespace = "http://schemas.ogf.org/nsi/2013/07/connection/types", className = "com.netmng.websvc.soap.param.types.QueryFailedType")
    @WebMethod(action = "http://schemas.ogf.org/nsi/2013/07/connection/service/queryNotificationFailed")
    @ResponseWrapper(localName = "acknowledgment", targetNamespace = "http://schemas.ogf.org/nsi/2013/07/connection/types", className = "com.netmng.websvc.soap.param.types.GenericAcknowledgmentType")
    public void queryNotificationFailed(
        @WebParam(name = "serviceException", targetNamespace = "")
        com.netmng.websvc.soap.svc.types.ServiceExceptionType serviceException
    ) throws com.netmng.websvc.soap.param._interface.ServiceException;

    
    
    
    
    
    
	
	
	
    /**
     * This error message is sent from a Provider NSA to Requester
     * NSA as an indication of the occurance of an error condition.
     * This  is in response to an original request from the associated
     * Requester NSA.
     *             
     */
    @RequestWrapper(localName = "error", targetNamespace = "http://schemas.ogf.org/nsi/2013/07/connection/types", className = "com.netmng.websvc.soap.param.types.GenericErrorType")
    @WebMethod(action = "http://schemas.ogf.org/nsi/2013/07/connection/service/error")
    @ResponseWrapper(localName = "acknowledgment", targetNamespace = "http://schemas.ogf.org/nsi/2013/07/connection/types", className = "com.netmng.websvc.soap.param.types.GenericAcknowledgmentType")
    public void error(
        @WebParam(name = "serviceException", targetNamespace = "")
        com.netmng.websvc.soap.svc.types.ServiceExceptionType serviceException
    ) throws com.netmng.websvc.soap.param._interface.ServiceException;

    /**
     * An autonomous message issued from a Provider NSA to Requester
     * NSA.  The acknowledgment indicates that the Requester NSA has
     * accepted the notification request for processing. There are no
     * associated confirmed or failed messages.
     *             
     */
    @RequestWrapper(localName = "messageDeliveryTimeout", targetNamespace = "http://schemas.ogf.org/nsi/2013/07/connection/types", className = "com.netmng.websvc.soap.param.types.MessageDeliveryTimeoutRequestType")
    @WebMethod(action = "http://schemas.ogf.org/nsi/2013/07/connection/service/messageDeliveryTimeout")
    @ResponseWrapper(localName = "acknowledgment", targetNamespace = "http://schemas.ogf.org/nsi/2013/07/connection/types", className = "com.netmng.websvc.soap.param.types.GenericAcknowledgmentType")
    public void messageDeliveryTimeout(
        @WebParam(name = "connectionId", targetNamespace = "")
        java.lang.String connectionId,
        @WebParam(name = "notificationId", targetNamespace = "")
        int notificationId,
        @WebParam(name = "timeStamp", targetNamespace = "")
        javax.xml.datatype.XMLGregorianCalendar timeStamp,
        @WebParam(name = "correlationId", targetNamespace = "")
        java.lang.String correlationId
    ) throws com.netmng.websvc.soap.param._interface.ServiceException;

    /**
     * An autonomous message issued from a Provider NSA to Requester
     * NSA.  The acknowledgment indicates that the Requester NSA has
     * accepted the notification request for processing. There are no
     * associated confirmed or failed messages.
     *             
     */
    @RequestWrapper(localName = "dataPlaneStateChange", targetNamespace = "http://schemas.ogf.org/nsi/2013/07/connection/types", className = "com.netmng.websvc.soap.param.types.DataPlaneStateChangeRequestType")
    @WebMethod(action = "http://schemas.ogf.org/nsi/2013/07/connection/service/dataPlaneStateChange")
    @ResponseWrapper(localName = "acknowledgment", targetNamespace = "http://schemas.ogf.org/nsi/2013/07/connection/types", className = "com.netmng.websvc.soap.param.types.GenericAcknowledgmentType")
    public void dataPlaneStateChange(
        @WebParam(name = "connectionId", targetNamespace = "")
        java.lang.String connectionId,
        @WebParam(name = "notificationId", targetNamespace = "")
        int notificationId,
        @WebParam(name = "timeStamp", targetNamespace = "")
        javax.xml.datatype.XMLGregorianCalendar timeStamp,
        @WebParam(name = "dataPlaneStatus", targetNamespace = "")
        com.netmng.websvc.soap.param.types.DataPlaneStatusType dataPlaneStatus
    ) throws com.netmng.websvc.soap.param._interface.ServiceException;

    /**
     * An autonomous error message issued from a Provider NSA to Requester
     * NSA.  The acknowledgment indicates that the Requester NSA has
     * accepted the notification request for processing. There are no
     * associated confirmed or failed messages.
     *             
     */
    @RequestWrapper(localName = "errorEvent", targetNamespace = "http://schemas.ogf.org/nsi/2013/07/connection/types", className = "com.netmng.websvc.soap.param.types.ErrorEventType")
    @WebMethod(action = "http://schemas.ogf.org/nsi/2013/07/connection/service/errorEvent")
    @ResponseWrapper(localName = "acknowledgment", targetNamespace = "http://schemas.ogf.org/nsi/2013/07/connection/types", className = "com.netmng.websvc.soap.param.types.GenericAcknowledgmentType")
    public void errorEvent(
        @WebParam(name = "connectionId", targetNamespace = "")
        java.lang.String connectionId,
        @WebParam(name = "notificationId", targetNamespace = "")
        int notificationId,
        @WebParam(name = "timeStamp", targetNamespace = "")
        javax.xml.datatype.XMLGregorianCalendar timeStamp,
        @WebParam(name = "event", targetNamespace = "")
        com.netmng.websvc.soap.param.types.EventEnumType event,
        @WebParam(name = "additionalInfo", targetNamespace = "")
        com.netmng.websvc.soap.svc.types.TypeValuePairListType additionalInfo,
        @WebParam(name = "serviceException", targetNamespace = "")
        com.netmng.websvc.soap.svc.types.ServiceExceptionType serviceException
    ) throws com.netmng.websvc.soap.param._interface.ServiceException;

}
