
package com.netmng.websvc.soap.svc.provider;

import javax.xml.ws.WebFault;
import com.netmng.websvc.soap.svc.types.ServiceExceptionType;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "serviceException", targetNamespace = "http://schemas.ogf.org/nsi/2013/07/connection/types")
public class ServiceException
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private ServiceExceptionType faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public ServiceException(String message, ServiceExceptionType faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public ServiceException(String message, ServiceExceptionType faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: org.ogf.schemas.nsi._2013._07.framework.types.ServiceExceptionType
     */
    public ServiceExceptionType getFaultInfo() {
        return faultInfo;
    }

}
